# Generated by Django 5.1 on 2025-06-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('capacityOfAirplans', models.IntegerField(default=0)),
                ('capacityOfPassengers', models.IntegerField(default=0)),
                ('evaluation', models.IntegerField(default=0)),
            ],
        ),
    ]
